name: Trigger auto deployment for llama-rag-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/llama-rag-api-AutoDeployTrigger-2f0aebff-34c9-409a-b744-d3238f1020c6.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Install azure-cli
        # You may pin to the exact commit or the version.
        # uses: pietrobolcato/install-azure-cli-action@9a10af1be5e3eb7931f48c0290364a131e7ecd70
        uses: pietrobolcato/install-azure-cli-action@v1.0.1
    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LLAMARAGAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: aiplatformdockerregistry.azurecr.io
          registryUsername: ${{ secrets.LLAMARAGAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LLAMARAGAPI_REGISTRY_PASSWORD }}
          containerAppName: llama-rag-api
          resourceGroup: ai-platform
          imageToBuild: aiplatformdockerregistry.azurecr.io/llama-rag-api:${{ github.sha }}
          dockerfilePath: Dockerfile
        env:
          KEY_VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
      
        

     

